### PR TITLE
Update package

### LINKED ISSUE #29: add `__version__` attribute to `chalk`
Adding `__version__` will allow checking version with `chalk.__version__`.

### LINKED ISSUE #30: add `MANIFEST.in` file for easy maintenance of PyPI package
The file `MANIFEST.in` is used to specify inclusion/exlcusion of files/folders in the source package. Adding it ensures unambiguous inclusion or exlcusion of specific files and folders from the repository.

### LINKED ISSUE #31: update `setup.py` for more informative source (PyPI) packaging
Currently `setup.py` uses `distutils` but the GitHub workflow installs setuptools.
- It is better to use setuptools than the old way of using distutils.
- Refer to:
  - https://stackoverflow.com/questions/25337706/setuptools-vs-distutils-why-is-distutils-still-a-thing
  - https://docs.python.org/3/distutils/setupscript.html (this points to the next link as the more updated one)
  - https://setuptools.pypa.io/en/latest/setuptools.html

Additionally, update various optional keyword parameters in `setup()` function call to make the PyPI  package publishing more informative.
  - [x] update setup function parameters
    - [x] add classifiers
    - [x] add license_files
    - [x] add project_urls
    - [x] add packages (use `find_packages()` from setuptools)
  - [x] add a `pyproject.toml` to the repository root

### LINKED ISSUE #32: update `.gitignore` file with standard python ignore rules
The current `.gitignore` lacks many of the standard python ignore rules. Please update this with a standard `.gitignore` (typically autogenerated by GitHub) and add any additional user-defined rules.

### LINKED ISSUE #33: add `py.typed` empty file to comply with PEP 561
## PEP 561 – Distributing and Packaging Type Information

This will help with type hinting. 

Add an empty file at the path: `chalk/py.typed`.

### References

- https://peps.python.org/pep-0561/
- https://mypy.readthedocs.io/en/stable/installed_packages.html
- https://blog.whtsky.me/tech/2021/dont-forget-py.typed-for-your-typed-python-package/
- https://stackoverflow.com/questions/62979389/is-there-a-best-practice-to-make-a-package-pep-561-compliant

### PR DESCRIPTION
**Pull request by sugatoray**
The following updates were made in this PR.

- [x] Add `__version__` to package: Closes #29 
  - [x] This will allow accessing the version with `chalk.__version__`.
  - [x] The version only needs maintaining inside `setup.py`

- [x] Update setup.py: Closes #31
  - [x] use `setuptools` instead of `disutils`
  - [x] update setup function parameters
    - [x] add classifiers
    - [x] add license_files
    - [x] add project_urls
    - [x] add packages (use `find_packages()` from setuptools)
  - [x] add a `pyproject.toml` to the repository root

- [x] Create `MANIFEST.in`: Closes #30
  > This ensure exclusion/inclusion of files/folders in the PyPI package from `MANIFEST.in` file.

- [x] Update .gitignore: Closes #32
  - [x] add standard python `.gitignore` with some user-defined extra ignore rules 

- [x] Add marker file for PEP 561: `chalk/py.typed`
  > Closes #33

- [x] Add a `dev_requirements.txt` file:
  - Add the following requirements to it, as these are not listed anywhere for quick dev-environment setup.
    - [x] `black`
    - [x] `flake8`
    - [x] `mypy`

### CODE REVIEW

**Comment by sugatoray** [comment]
@danoneata Is the library only supported for OSX and Linux platforms (not Windows)?

**Comment by danoneata** [comment]
Thanks a lot for the very helpful pull request!

The `py.typed` file shouldn't be also added to the `package_data` in the `setup.py`? Or is it enough that is referenced by the `MANIFEST.in` file?

> Is the library only supported for OSX and Linux platforms (not Windows)?

We have only tried it on OSX and Linux for the time being. In principle, if the dependencies work on Windows, then `chalk` should also run on Windows.

**Comment by sugatoray** [comment]
> The py.typed file shouldn't be also added to the package_data in the setup.py? Or is it enough that is referenced by the MANIFEST.in file?

Just adding to `MANIFEST.in` is sufficient. If you didn't have `MANIFEST.in`, then yes, you will need to add it to `package_data` in setup.py. 

But please don't merge it yet. I would like to test a few things first. In the meantime, if you have any review-suggestions, please let me know.

**Comment by sugatoray** [comment]
> We have only tried it on OSX and Linux for the time being. In principle, if the dependencies work on Windows, then chalk should also run on Windows

🔥 The conda-forge PR to add `chalk-diagrams` from PyPI failed during the Windows build. 

👉 A few things you can avoid to avert possible Windows/Unix failures: the first thing I would suggest you to do is avoid using naked path strings wherever possible. Please use `os.path.relpath`, `os.path.abspath`, `os.path.join` to create the path string you would use. This ensures os-specific path-separators are being used out-of-the-box. 

👀 I am not sure if this is what causes the build failure there (the conda-forge PR). But this is something, I would suggest you to adopt early on as a best practice and add it to any contribution guidelines.

**Comment by danoneata** [comment]
Hello! I've made some small tweaks, but the main issue is that the code is failing the build; that is, when running

```bash
python3 -m build
```

I end up with the following error trace

```
* Creating venv isolated environment...
* Installing packages in isolated environment... (setuptools>=42, wheel)
* Getting dependencies for sdist...
Traceback (most recent call last):
  File "/Users/doneata/work/trinket/venv/lib/python3.8/site-packages/pep517/in_process/_in_process.py", line 363, in <module>
    main()
  File "/Users/doneata/work/trinket/venv/lib/python3.8/site-packages/pep517/in_process/_in_process.py", line 345, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/Users/doneata/work/trinket/venv/lib/python3.8/site-packages/pep517/in_process/_in_process.py", line 297, in get_requires_for_build_sdist
    return hook(config_settings)
  File "/private/var/folders/md/0jyhswhj4yq33dshj282qw2r0000gn/T/build-env-jmcrgvbw/lib/python3.8/site-packages/setuptools/build_meta.py", line 181, in get_requires_for_build_sdist
    return self._get_build_requires(config_settings, requirements=[])
  File "/private/var/folders/md/0jyhswhj4yq33dshj282qw2r0000gn/T/build-env-jmcrgvbw/lib/python3.8/site-packages/setuptools/build_meta.py", line 159, in _get_build_requires
    self.run_setup()
  File "/private/var/folders/md/0jyhswhj4yq33dshj282qw2r0000gn/T/build-env-jmcrgvbw/lib/python3.8/site-packages/setuptools/build_meta.py", line 174, in run_setup
    exec(compile(code, __file__, 'exec'), locals())
  File "setup.py", line 3, in <module>
    import chalk as ck
ModuleNotFoundError: No module named 'chalk'

ERROR Backend subproccess exited when trying to invoke get_requires_for_build_sdist
```

Do you have any advice on how to fix this?

**Comment by sugatoray** [comment]
Yes. I think I know why this is happening. I will be able work on this over this weekend. Let me ping you here, to give it a test run, once am done.

**Comment by sugatoray** [comment]
:rocket: :fire: An update: `chalk-diagrams` is now available on `conda-forge` channel and can be installed with conda as follows.

```sh
conda install -c conda-forge chalk-diagrams
```

> :hand: NOTE: For now, conda-forge version of the library only offers the set of libraries listed under `install_requires` in `setup.py`. 

cc: @danoneata

**Comment by sugatoray** [comment]
@danoneata It is fixed now.

Try running the following snippet.

```python
import chalk
from typing import Any
from PIL import Image
from colour import Color
from chalk import *

print(f"{chalk.__name__} version: {chalk.__version__}") 

papaya = Color("#ff9700")
blue = Color("#005FDB")

d = circle(1).fill_color(papaya)
filepath = "examples/output/intro-01-a.png"

def render_and_show(d: Any, filepath: str, height=64):
  d.render(filepath, height=height)
  Image.open(filepath).show()

render_and_show(d, filepath, height=64)
```

**Comment by danoneata** [comment]
Thanks a lot for the very useful updates @sugatoray ! Much appreciated! 🙏

**Pull request merged**
