### PR TITLE
Arrows, connection, and closed paths

### PR DESCRIPTION
**Pull request by srush**
This PR makes an attempt to add Arrows following mostly the Diagrams API. https://diagrams.github.io/doc/arrow.html

I tried to mimic Diagrams here as it is complex. It mostly builds from a simple arrow primitive to more complex structures like connection. 

image

image

(same code in haskell. their code is a bit cleaner because they use lenses for `ArrowOpts`, but I think dataclasses is fine. Maybe we can make a `Stylable` class for creating Style dataclasses incrementally.)

```haskell
oct  = octagon 1 # lc darkgray # lw ultraThick # showOrigin
dias = oct # named "first" ||| strut 3 ||| oct # named "second"

-- Connect two diagrams and two points on their trails.
ex12 = dias # connect' (with & lengths .~ veryLarge) "first" "second"
            # connectPerim' (with & lengths .~ veryLarge)
       "first" "second" (15/16 @@ turn) (9/16 @@ turn)

-- Place an arrow at (0,0) the size and direction of (0,1).
ex3 = arrowAt origin unit_Y

example2 = (ex12 <> ex3) # centerXY # pad 1.1
```

Changes:

* Use traces to implement connect_outer and connect_perim
* Draws arrow heads with the diagram framework, no relying on backend
* Allows trails for jagged arrows and arc_between for curved arrows (we can replace this when trails allows curves).
* ArrowOpts class mimics the datastructure from Diagram for arrow options. 
* Replaces older connect and connect_outer api.
* ArrowHead is specialized to only draw after we know the size. This will become something like "scale-invariant."
* Add a `get_subdiagram_trace` for the tournament diagram. 

* Also changes the renderers to close paths if the last and first are the same position. This should be handled better in the future. 

Issues:

* Need to better understand how arrow-heads should be sized. 
* It's all in Core, because I wanted it to be on the Diagram class. This needs to be fixed see - > https://github.com/danoneata/chalk/issues/89
* The type system is still not great. Will fix after we pull things into individual files.

### CODE REVIEW

**Comment by danoneata** [comment]
Thanks! That's awesome! At a first glance, it looks really tidy! I'll take a closer look at the code tomorrow. Just a few comments:

- It seems that the directions for `connect_perim` don't agree with those specified by `Trail`s; I've tried to have a look, but couldn't quickly find the source of discrepancy. Here is an example:
```python
c = circle(0.5).fill_color(orange).named("c")
c = (
    c.connect_perim("c", "c", unit_x, unit_y, ArrowOpts(arcHeight=0.5))
    + trail.unit_x.scale(0.5).stroke()
    + trail.unit_y.scale(0.5).stroke()
)
```
o
- This is minor, but for `ArrowOpts`'s attributes would you mind using `snake_case` (instead of `camelCase`), for consistency with the rest of the code?

**Comment by srush** [comment]
Okay, think these are fixed. 

The issue with the camel case seems to be have been that trace_v returned negative traces first. I think it maybe shouldn't return negatives? seems to go against the point. 

image

**Comment by danoneata** [comment]
I think the previous behaviour, of returning the smallest (most negative) distance was consistent with `traceV` from `diagrams`.

image

I've took the liberty and added the `max` variants (`max_trace_v` and `max_trace_p`), which return the points in the direction of the given vector, and I've used those in the `connect` functions.

Also, I've noticed that `connect_outer` used `tr1` with `env2`:
```python
vs = tr1.trace_v(env2.center, -v) + env2.center
```
Was that correct? I've changed that to apply `tr1` to `env1`.

Finally, I think I've stumbled upon a bug caused by the interplay of `planar.Ray`, which automatically scales the direction to unit length, and the `line_segment` intersection function, which assumes that the length of the segment is preserved in the corresponding `Ray`'s `direction`. i'll open a separate issue for this.

**Comment by danoneata** [comment]
> I think that was on purpose. For connect outside we want the point on the trace of t1 as seen from env2 right? Although maybe it is better to replicate your behavior of checking both from a middle point. When are they different?

Ah, okay, sorry! I've reverted to the previous way of computing the points on the trace:
```diff
-        ps = tr1.max_trace_p(env1.center, v)
-        pe = tr2.max_trace_p(env2.center, -v)
+        ps = tr1.trace_p(env2.center, -v)
+        pe = tr2.trace_p(env1.center, v)
```
But I think they might be equivalent; at least, I haven't observed a difference between the two on our examples.

I think the version that used the midpoint was based on diagrams, see [`connectOutside'`](https://hackage.haskell.org/package/diagrams-lib-1.4.5.1/docs/src/Diagrams.TwoD.Arrow.html#connectOutside%27). I'm not sure I see what are the trade-offs between our current version the midpoint one.

**Comment by srush** [comment]
Gotcha. Let's do midpoint then. As always, I'm sure there is some case with non-centered, non-convex diagrams where the simple solution fails.

**Comment by danoneata** [comment]
Okay, I've made the following changes:
- reverted to using `midpoint` in `connect_outside`
- fixed the issue described in #91 
- made some other small changes for consistency.

I'll let you have a final look on these changes, but otherwise I'm happy with the PR (thanks again!), so feel free to merge at your will.

**Pull request merged**
